import type { UserConfig } from 'vite';
const config: UserConfig = {
    build: {
        target: 'es2023',
        lib: {
            entry: {
                'workflow-catalog': 'src/workflows/ComponentRegistry.ts',
                'workflow-component-types': 'src/workflows/ComponentTypes.ts',
                'workflow-validation': 'src/workflows/GraphValidation.ts',
                'workflow-graph-types': 'src/workflows/GraphTypes.ts',
                'workflow-ports': 'src/workflows/PortCompatibility.ts',
                'workflow-schemas': 'src/workflows/Schemas.ts',
                'workflow-schema-types': 'src/workflows/SchemaTypes.ts',
                'workflow-values': 'src/workflows/SchemaValues.ts',
                'workflow-types': 'src/workflows/WorkflowTypes.ts',
                'workflow-codec': 'src/workflows/WorkflowCodec.ts',
                'workflow-requests': 'src/workflows/WorkflowRequests.ts',
                'workflow-request-codec': 'src/workflows/WorkflowRequestCodec.ts',
                'workflow-resources': 'src/workflows/ResourceTypes.ts',
                'workflow-resource-codec': 'src/workflows/ResourceBindingCodec.ts',
                'workflow-resource-readiness': 'src/workflows/ResourceReadiness.ts',
                'nexa-transport': 'src/networking/NexaClient.ts',
                protocol: 'src/protocol/Protocol.ts',
                media: 'src/media/NexaMedia.ts',
                events: 'src/protocol/Events.ts',
                office: 'src/office/OfficeProtocol.ts',
                company: 'src/company/CompanyProtocol.ts',
                projects: 'src/company/CompanyProjectProtocol.ts',
                'project-types': 'src/company/CompanyProjectTypes.ts',
                'company-types': 'src/company/CompanyTypes.ts',
                'employee-results': 'src/company/CompanyEmployeeTypes.ts',
                'company-hosts': 'src/company/CompanyHostTypes.ts',
                errors: 'src/networking/TransportError.ts',
            },
            formats: ['es'],
        },
        sourcemap: true,
    },
};
export default config;
