import type { UserConfig } from 'vite';
const config: UserConfig = {
    build: {
        target: 'es2023',
        lib: {
            entry: {
                'chat-graph': 'src/graphs/ChatGraph.ts',
                'workflow-model-effort': 'src/workflows/ModelEffort.ts',
                'workflow-application-models': 'src/workflows/terminal/ApplicationModels.ts',
                'workflow-applications': 'src/workflows/terminal/Applications.ts',
                'workflow-terminal-types': 'src/workflows/terminal/TerminalTypes.ts',
                'reverse-investigation': 'src/reverse/ReverseInvestigation.ts',
                'workflow-planning-alignment': 'src/workflows/planning/PlanningAlignment.ts',
                'workflow-planning-sources': 'src/workflows/planning/PlanningSources.ts',
                'workflow-planning-types': 'src/workflows/planning/PlanningTypes.ts',
                'workflow-planning-codec': 'src/workflows/planning/PlanningCodec.ts',
                'workflow-planning-edits': 'src/workflows/planning/PlanningEdits.ts',
                'workflow-artifacts': 'src/workflows/runtime/ArtifactDownload.ts',
                'workflow-publication-codec': 'src/workflows/PublicationCodec.ts',
                'workflow-run-types': 'src/workflows/runtime/RunTypes.ts',
                'workflow-run-requests': 'src/workflows/runtime/RunRequests.ts',
                'workflow-run-codec': 'src/workflows/runtime/RunCodec.ts',
                'workflow-run-request-codec': 'src/workflows/runtime/RunRequestCodec.ts',
                'workflow-models': 'src/workflows/WorkflowModels.ts',
                'workflow-image-quote': 'src/workflows/WorkflowImageQuote.ts',
                'workflow-image-resolution': 'src/workflows/ImageResolution.ts',
                'workflow-image-policy': 'src/workflows/ImageModelPolicy.ts',
                'workflow-model-policy': 'src/workflows/ModelResolution.ts',
                'workflow-catalog': 'src/workflows/ComponentRegistry.ts',
                'workflow-component-types': 'src/workflows/ComponentTypes.ts',
                'workflow-validation': 'src/workflows/GraphValidation.ts',
                'workflow-graph-types': 'src/workflows/GraphTypes.ts',
                'workflow-ports': 'src/workflows/PortCompatibility.ts',
                'workflow-schemas': 'src/workflows/Schemas.ts',
                'workflow-schema-types': 'src/workflows/SchemaTypes.ts',
                'workflow-values': 'src/workflows/SchemaValues.ts',
                'workflow-group-types': 'src/workflows/WorkflowGroupTypes.ts',
                'workflow-group-codec': 'src/workflows/WorkflowGroupCodec.ts',
                'workflow-types': 'src/workflows/WorkflowTypes.ts',
                'workflow-codec': 'src/workflows/WorkflowCodec.ts',
                'workflow-requests': 'src/workflows/WorkflowRequests.ts',
                'workflow-request-codec': 'src/workflows/WorkflowRequestCodec.ts',
                'workflow-resources': 'src/workflows/ResourceTypes.ts',
                'workflow-resource-codec': 'src/workflows/ResourceBindingCodec.ts',
                'workflow-resource-readiness': 'src/workflows/ResourceReadiness.ts',
                'nexa-transport': 'src/networking/NexaClient.ts',
                protocol: 'src/protocol/Protocol.ts',
                media: 'src/media/NexaMedia.ts',
                events: 'src/protocol/Events.ts',
                office: 'src/office/OfficeProtocol.ts',
                company: 'src/company/CompanyProtocol.ts',
                projects: 'src/company/CompanyProjectProtocol.ts',
                'project-types': 'src/company/CompanyProjectTypes.ts',
                'company-types': 'src/company/CompanyTypes.ts',
                'employee-results': 'src/company/CompanyEmployeeTypes.ts',
                'company-hosts': 'src/company/CompanyHostTypes.ts',
                errors: 'src/networking/TransportError.ts',
            },
            formats: ['es'],
        },
        sourcemap: true,
    },
};
export default config;
