import * as validators from './Validators.js';
import type { Validator } from './Validators.js';
import type { MethodName } from './Protocol.js';
/** Validators for one method. */
export interface MethodValidation {
    readonly params: Validator;
    readonly result: Validator;
}
/** Exhaustive RPC boundary validators. */
export const methodValidators: Readonly<Record<MethodName, MethodValidation>> = {
    'accounts.create': { params: validators.params0, result: validators.result0 },
    'accounts.list': { params: validators.params1, result: validators.result1 },
    'accounts.remove': { params: validators.params2, result: validators.result2 },
    'accounts.usage': { params: validators.params3, result: validators.result3 },
    'agent.ask': { params: validators.params4, result: validators.result4 },
    'agent.stream': { params: validators.params5, result: validators.result5 },
    'agents.define': { params: validators.params6, result: validators.result6 },
    'agents.list': { params: validators.params7, result: validators.result7 },
    'approvals.list': { params: validators.params8, result: validators.result8 },
    'approvals.resolve': { params: validators.params9, result: validators.result9 },
    'channels.deadLetters.list': { params: validators.params10, result: validators.result10 },
    'channels.list': { params: validators.params11, result: validators.result11 },
    'channels.status': { params: validators.params12, result: validators.result12 },
    'config.get': { params: validators.params13, result: validators.result13 },
    'config.set': { params: validators.params14, result: validators.result14 },
    'config.unset': { params: validators.params15, result: validators.result15 },
    connect: { params: validators.params16, result: validators.result16 },
    'credit.budgets': { params: validators.params17, result: validators.result17 },
    'credit.removeBudget': { params: validators.params18, result: validators.result18 },
    'credit.resetAllowance': { params: validators.params19, result: validators.result19 },
    'credit.resetHistory': { params: validators.params20, result: validators.result20 },
    'credit.resets': { params: validators.params21, result: validators.result21 },
    'credit.setBudget': { params: validators.params22, result: validators.result22 },
    'credit.summary': { params: validators.params23, result: validators.result23 },
    'credit.wallet': { params: validators.params24, result: validators.result24 },
    'credit.walletHistory': { params: validators.params25, result: validators.result25 },
    'data.upload.cancel': { params: validators.params26, result: validators.result26 },
    'data.upload.chunk': { params: validators.params27, result: validators.result27 },
    'data.upload.finish': { params: validators.params28, result: validators.result28 },
    'data.upload.start': { params: validators.params29, result: validators.result29 },
    'devices.approve': { params: validators.params30, result: validators.result30 },
    'devices.list': { params: validators.params31, result: validators.result31 },
    'devices.reject': { params: validators.params32, result: validators.result32 },
    'devices.revoke': { params: validators.params33, result: validators.result33 },
    health: { params: validators.params34, result: validators.result34 },
    'jobs.add': { params: validators.params35, result: validators.result35 },
    'jobs.list': { params: validators.params36, result: validators.result36 },
    'jobs.remove': { params: validators.params37, result: validators.result37 },
    'logs.tail': { params: validators.params38, result: validators.result38 },
    'media.acknowledge': { params: validators.params39, result: validators.result39 },
    'roblox.credentials.remove': { params: validators.params40, result: validators.result40 },
    'roblox.credentials.set': { params: validators.params41, result: validators.result41 },
    'roblox.credentials.status': { params: validators.params42, result: validators.result42 },
    'roblox.telemetry.funnel': { params: validators.params43, result: validators.result43 },
    'roblox.telemetry.performance': { params: validators.params44, result: validators.result44 },
    'roblox.telemetry.projects': { params: validators.params45, result: validators.result45 },
    'sessions.delete': { params: validators.params46, result: validators.result46 },
    'sessions.download': { params: validators.params47, result: validators.result47 },
    'sessions.files': { params: validators.params48, result: validators.result48 },
    'sessions.get': { params: validators.params49, result: validators.result49 },
    'sessions.list': { params: validators.params50, result: validators.result50 },
    'sessions.messages': { params: validators.params51, result: validators.result51 },
    'sessions.subscribe': { params: validators.params52, result: validators.result52 },
    'sessions.unsubscribe': { params: validators.params53, result: validators.result53 },
    'shares.create': { params: validators.params54, result: validators.result54 },
    'shares.list': { params: validators.params55, result: validators.result55 },
    'shares.remove': { params: validators.params56, result: validators.result56 },
    'shares.setMember': { params: validators.params57, result: validators.result57 },
    'tasks.cancel': { params: validators.params58, result: validators.result58 },
    'tasks.get': { params: validators.params59, result: validators.result59 },
    'tasks.list': { params: validators.params60, result: validators.result60 },
    'teams.create': { params: validators.params61, result: validators.result61 },
    'teams.list': { params: validators.params62, result: validators.result62 },
    'teams.remove': { params: validators.params63, result: validators.result63 },
    'teams.setMember': { params: validators.params64, result: validators.result64 },
    'voice.audio': { params: validators.params65, result: validators.result65 },
    'voice.start': { params: validators.params66, result: validators.result66 },
    'voice.stop': { params: validators.params67, result: validators.result67 },
    'workspaces.create': { params: validators.params68, result: validators.result68 },
    'workspaces.describe': { params: validators.params69, result: validators.result69 },
    'workspaces.destroy': { params: validators.params70, result: validators.result70 },
    'workspaces.list': { params: validators.params71, result: validators.result71 },
};
