import * as validators from './Validators.js';
import type { Validator } from './Validators.js';
import type { MethodName } from './Protocol.js';
/** Validators for one method. */
export interface MethodValidation {
    readonly params: Validator;
    readonly result: Validator;
}
/** Exhaustive RPC boundary validators. */
export const methodValidators: Readonly<Record<MethodName, MethodValidation>> = {
    'accounts.create': { params: validators.params0, result: validators.result0 },
    'accounts.list': { params: validators.params1, result: validators.result1 },
    'accounts.remove': { params: validators.params2, result: validators.result2 },
    'accounts.usage': { params: validators.params3, result: validators.result3 },
    'agent.ask': { params: validators.params4, result: validators.result4 },
    'agent.steer': { params: validators.params5, result: validators.result5 },
    'agent.stream': { params: validators.params6, result: validators.result6 },
    'agents.define': { params: validators.params7, result: validators.result7 },
    'agents.list': { params: validators.params8, result: validators.result8 },
    'agents.personal.list': { params: validators.params9, result: validators.result9 },
    'agents.personal.remove': { params: validators.params10, result: validators.result10 },
    'agents.personal.save': { params: validators.params11, result: validators.result11 },
    'approvals.list': { params: validators.params12, result: validators.result12 },
    'approvals.resolve': { params: validators.params13, result: validators.result13 },
    'channels.deadLetters.list': { params: validators.params14, result: validators.result14 },
    'channels.list': { params: validators.params15, result: validators.result15 },
    'channels.status': { params: validators.params16, result: validators.result16 },
    'config.get': { params: validators.params17, result: validators.result17 },
    'config.set': { params: validators.params18, result: validators.result18 },
    'config.unset': { params: validators.params19, result: validators.result19 },
    connect: { params: validators.params20, result: validators.result20 },
    'credit.budgets': { params: validators.params21, result: validators.result21 },
    'credit.removeBudget': { params: validators.params22, result: validators.result22 },
    'credit.resetAllowance': { params: validators.params23, result: validators.result23 },
    'credit.resetHistory': { params: validators.params24, result: validators.result24 },
    'credit.resets': { params: validators.params25, result: validators.result25 },
    'credit.setBudget': { params: validators.params26, result: validators.result26 },
    'credit.summary': { params: validators.params27, result: validators.result27 },
    'credit.wallet': { params: validators.params28, result: validators.result28 },
    'credit.walletHistory': { params: validators.params29, result: validators.result29 },
    'data.upload.cancel': { params: validators.params30, result: validators.result30 },
    'data.upload.chunk': { params: validators.params31, result: validators.result31 },
    'data.upload.finish': { params: validators.params32, result: validators.result32 },
    'data.upload.start': { params: validators.params33, result: validators.result33 },
    'devices.approve': { params: validators.params34, result: validators.result34 },
    'devices.list': { params: validators.params35, result: validators.result35 },
    'devices.reject': { params: validators.params36, result: validators.result36 },
    'devices.revoke': { params: validators.params37, result: validators.result37 },
    health: { params: validators.params38, result: validators.result38 },
    'jobs.add': { params: validators.params39, result: validators.result39 },
    'jobs.list': { params: validators.params40, result: validators.result40 },
    'jobs.remove': { params: validators.params41, result: validators.result41 },
    'logs.tail': { params: validators.params42, result: validators.result42 },
    'media.acknowledge': { params: validators.params43, result: validators.result43 },
    'office.ownerProof': { params: validators.params44, result: validators.result44 },
    'processes.input': { params: validators.params45, result: validators.result45 },
    'processes.list': { params: validators.params46, result: validators.result46 },
    'processes.log': { params: validators.params47, result: validators.result47 },
    'processes.resize': { params: validators.params48, result: validators.result48 },
    'processes.stop': { params: validators.params49, result: validators.result49 },
    'reverse.browser': { params: validators.params50, result: validators.result50 },
    'reverse.browser.modules': { params: validators.params51, result: validators.result51 },
    'reverse.browser.screenshot': { params: validators.params52, result: validators.result52 },
    'reverse.browser.sources': { params: validators.params53, result: validators.result53 },
    'reverse.browser.structure': { params: validators.params54, result: validators.result54 },
    'reverse.catalog': { params: validators.params55, result: validators.result55 },
    'reverse.evidence': { params: validators.params56, result: validators.result56 },
    'reverse.functions': { params: validators.params57, result: validators.result57 },
    'reverse.graph': { params: validators.params58, result: validators.result58 },
    'reverse.inspect': { params: validators.params59, result: validators.result59 },
    'reverse.network': { params: validators.params60, result: validators.result60 },
    'reverse.network.detail': { params: validators.params61, result: validators.result61 },
    'roblox.credentials.remove': { params: validators.params62, result: validators.result62 },
    'roblox.credentials.set': { params: validators.params63, result: validators.result63 },
    'roblox.credentials.status': { params: validators.params64, result: validators.result64 },
    'roblox.telemetry.funnel': { params: validators.params65, result: validators.result65 },
    'roblox.telemetry.performance': { params: validators.params66, result: validators.result66 },
    'roblox.telemetry.projects': { params: validators.params67, result: validators.result67 },
    'sessions.delete': { params: validators.params68, result: validators.result68 },
    'sessions.download': { params: validators.params69, result: validators.result69 },
    'sessions.files': { params: validators.params70, result: validators.result70 },
    'sessions.get': { params: validators.params71, result: validators.result71 },
    'sessions.input': { params: validators.params72, result: validators.result72 },
    'sessions.list': { params: validators.params73, result: validators.result73 },
    'sessions.messages': { params: validators.params74, result: validators.result74 },
    'sessions.pin': { params: validators.params75, result: validators.result75 },
    'sessions.pins': { params: validators.params76, result: validators.result76 },
    'sessions.rename': { params: validators.params77, result: validators.result77 },
    'sessions.retry': { params: validators.params78, result: validators.result78 },
    'sessions.subscribe': { params: validators.params79, result: validators.result79 },
    'sessions.transcript': { params: validators.params80, result: validators.result80 },
    'sessions.unpin': { params: validators.params81, result: validators.result81 },
    'sessions.unsubscribe': { params: validators.params82, result: validators.result82 },
    'shares.create': { params: validators.params83, result: validators.result83 },
    'shares.list': { params: validators.params84, result: validators.result84 },
    'shares.remove': { params: validators.params85, result: validators.result85 },
    'shares.setMember': { params: validators.params86, result: validators.result86 },
    'tasks.cancel': { params: validators.params87, result: validators.result87 },
    'tasks.get': { params: validators.params88, result: validators.result88 },
    'tasks.list': { params: validators.params89, result: validators.result89 },
    'teams.create': { params: validators.params90, result: validators.result90 },
    'teams.list': { params: validators.params91, result: validators.result91 },
    'teams.remove': { params: validators.params92, result: validators.result92 },
    'teams.setMember': { params: validators.params93, result: validators.result93 },
    'voice.audio': { params: validators.params94, result: validators.result94 },
    'voice.start': { params: validators.params95, result: validators.result95 },
    'voice.stop': { params: validators.params96, result: validators.result96 },
    'workflows.attention.list': { params: validators.params97, result: validators.result97 },
    'workflows.catalog': { params: validators.params98, result: validators.result98 },
    'workflows.create': { params: validators.params99, result: validators.result99 },
    'workflows.delete': { params: validators.params100, result: validators.result100 },
    'workflows.list': { params: validators.params101, result: validators.result101 },
    'workflows.models': { params: validators.params102, result: validators.result102 },
    'workflows.models.image.quote': { params: validators.params103, result: validators.result103 },
    'workflows.models.image.resolve': {
        params: validators.params104,
        result: validators.result104,
    },
    'workflows.models.refresh': { params: validators.params105, result: validators.result105 },
    'workflows.models.resolve': { params: validators.params106, result: validators.result106 },
    'workflows.planning.cancel': { params: validators.params107, result: validators.result107 },
    'workflows.planning.history': { params: validators.params108, result: validators.result108 },
    'workflows.planning.read': { params: validators.params109, result: validators.result109 },
    'workflows.planning.send': { params: validators.params110, result: validators.result110 },
    'workflows.planning.sources': { params: validators.params111, result: validators.result111 },
    'workflows.publications.check': { params: validators.params112, result: validators.result112 },
    'workflows.publications.list': { params: validators.params113, result: validators.result113 },
    'workflows.publications.publish': {
        params: validators.params114,
        result: validators.result114,
    },
    'workflows.publications.read': { params: validators.params115, result: validators.result115 },
    'workflows.publications.run': { params: validators.params116, result: validators.result116 },
    'workflows.read': { params: validators.params117, result: validators.result117 },
    'workflows.record': { params: validators.params118, result: validators.result118 },
    'workflows.records': { params: validators.params119, result: validators.result119 },
    'workflows.runs.agent.control': { params: validators.params120, result: validators.result120 },
    'workflows.runs.agent.input': { params: validators.params121, result: validators.result121 },
    'workflows.runs.agent.read': { params: validators.params122, result: validators.result122 },
    'workflows.runs.applications.check': {
        params: validators.params123,
        result: validators.result123,
    },
    'workflows.runs.applications.setup': {
        params: validators.params124,
        result: validators.result124,
    },
    'workflows.runs.approval.decide': {
        params: validators.params125,
        result: validators.result125,
    },
    'workflows.runs.artifact': { params: validators.params126, result: validators.result126 },
    'workflows.runs.artifacts': { params: validators.params127, result: validators.result127 },
    'workflows.runs.attempts': { params: validators.params128, result: validators.result128 },
    'workflows.runs.cancel': { params: validators.params129, result: validators.result129 },
    'workflows.runs.events': { params: validators.params130, result: validators.result130 },
    'workflows.runs.inputs': { params: validators.params131, result: validators.result131 },
    'workflows.runs.list': { params: validators.params132, result: validators.result132 },
    'workflows.runs.loopSpending': { params: validators.params133, result: validators.result133 },
    'workflows.runs.output': { params: validators.params134, result: validators.result134 },
    'workflows.runs.question.answer': {
        params: validators.params135,
        result: validators.result135,
    },
    'workflows.runs.question.read': { params: validators.params136, result: validators.result136 },
    'workflows.runs.questions': { params: validators.params137, result: validators.result137 },
    'workflows.runs.read': { params: validators.params138, result: validators.result138 },
    'workflows.runs.start': { params: validators.params139, result: validators.result139 },
    'workflows.runs.steps': { params: validators.params140, result: validators.result140 },
    'workflows.runs.terminal.command': {
        params: validators.params141,
        result: validators.result141,
    },
    'workflows.runs.terminal.read': { params: validators.params142, result: validators.result142 },
    'workflows.save': { params: validators.params143, result: validators.result143 },
    'workflows.schedules.disable': { params: validators.params144, result: validators.result144 },
    'workflows.schedules.enable': { params: validators.params145, result: validators.result145 },
    'workflows.schedules.preview': { params: validators.params146, result: validators.result146 },
    'workflows.schedules.read': { params: validators.params147, result: validators.result147 },
    'workflows.validate': { params: validators.params148, result: validators.result148 },
    'workspaces.create': { params: validators.params149, result: validators.result149 },
    'workspaces.describe': { params: validators.params150, result: validators.result150 },
    'workspaces.destroy': { params: validators.params151, result: validators.result151 },
    'workspaces.list': { params: validators.params152, result: validators.result152 },
};
